<?php

// --------------------------------------------------
// Facilities Toolbox - Management Reports
// --------------------------------------------------
//
// v0.2 reporting is now generated by the C# API.
// The portal selects a date, renders the management
// report and exposes the matching CSV export.
// --------------------------------------------------

require_once __DIR__ . "/includes/api.php";

$saTimezone = new DateTimeZone("Africa/Johannesburg");
$today = new DateTime("now", $saTimezone);

$selectedDate = trim($_GET["date"] ?? $today->format("Y-m-d"));

// Keep the date query predictable before sending it to
// the API. Invalid values fall back to today.
$dateObject = DateTime::createFromFormat("Y-m-d", $selectedDate, $saTimezone);

if (!$dateObject || $dateObject->format("Y-m-d") !== $selectedDate) {
    $selectedDate = $today->format("Y-m-d");
}

$result = facilitiesApiRequest(
    "GET",
    "/api/reports/daily?date=" . rawurlencode($selectedDate)
);

$report =
    $result["success"] && is_array($result["data"])
        ? $result["data"]
        : [];

$errorMessage = $result["success"]
    ? null
    : $result["message"];

$rows = is_array($report["rows"] ?? null)
    ? $report["rows"]
    : [];

$downloadUrl =
    "http://localhost:5209/api/reports/daily.csv?date="
    . rawurlencode($selectedDate);

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports | Facilities Toolbox</title>
    <link rel="stylesheet" href="assets/app.css">
</head>
<body>
<div class="app-shell">
    <aside class="sidebar">
        <div class="brand">
            <div class="brand-mark">FT</div>
            <h1>Facilities Toolbox</h1>
            <p>The Tech Alchemy Lab</p>
        </div>

        <div class="nav-section-label">Operations</div>
        <nav>
            <a class="nav-link" href="index.php">Dashboard</a>
            <a class="nav-link" href="employees.php">Employees</a>
            <a class="nav-link" href="attendance.php">Attendance</a>
            <a class="nav-link active" href="reports.php">Reports</a>
        </nav>

        <div class="nav-section-label">System</div>
        <nav>
            <a class="nav-link" href="departments.php">Departments</a>
            <a class="nav-link" href="settings.php">Settings</a>
        </nav>

        <div class="sidebar-footer">v0.2 Operations Intelligence</div>
    </aside>

    <main class="main">
        <header class="topbar">
            <div>
                <p class="eyebrow">Management Reporting</p>
                <h2 class="page-title">Daily Attendance Report</h2>
                <p class="page-subtitle">
                    Date-scoped workforce attendance, punctuality and completed-hours intelligence.
                </p>
            </div>
            <a class="action-link" href="<?= htmlspecialchars($downloadUrl) ?>">Export CSV</a>
        </header>

        <?php if ($errorMessage): ?>
            <div class="notice error"><?= htmlspecialchars($errorMessage) ?></div>
        <?php endif; ?>

        <section class="panel" style="margin-bottom:18px;">
            <form method="GET" class="form-grid">
                <div class="field">
                    <label for="date">Report Date</label>
                    <input id="date" type="date" name="date" value="<?= htmlspecialchars($selectedDate) ?>">
                </div>
                <div style="display:flex;align-items:end;">
                    <button class="button primary" type="submit">Load Report</button>
                </div>
            </form>
        </section>

        <section class="grid kpi-grid">
            <article class="kpi-card">
                <p class="kpi-label">Attendance Rate</p>
                <p class="kpi-value"><?= number_format((float)($report["attendanceRate"] ?? 0), 1) ?>%</p>
                <p class="kpi-meta"><?= (int)($report["seenEmployees"] ?? 0) ?> staff seen</p>
            </article>

            <article class="kpi-card">
                <p class="kpi-label">Present</p>
                <p class="kpi-value"><?= (int)($report["presentNow"] ?? 0) ?></p>
                <p class="kpi-meta">Latest state IN</p>
            </article>

            <article class="kpi-card">
                <p class="kpi-label">Late</p>
                <p class="kpi-value"><?= (int)($report["lateEmployees"] ?? 0) ?></p>
                <p class="kpi-meta">Shift <?= htmlspecialchars($report["shiftStart"] ?? "--") ?> + <?= (int)($report["graceMinutes"] ?? 0) ?>m grace</p>
            </article>

            <article class="kpi-card">
                <p class="kpi-label">Completed Hours</p>
                <p class="kpi-value"><?= number_format((float)($report["totalCompletedHours"] ?? 0), 1) ?>h</p>
                <p class="kpi-meta">Completed IN → OUT sessions</p>
            </article>
        </section>

        <section class="panel">
            <div class="panel-header">
                <div>
                    <h3 class="panel-title">Employee Day View</h3>
                    <p class="panel-description">
                        <?= htmlspecialchars($selectedDate) ?> · all employee records included for management context.
                    </p>
                </div>
            </div>

            <?php if (!$rows): ?>
                <div class="empty-state">No report rows available.</div>
            <?php else: ?>
                <div class="table-wrap">
                    <table>
                        <thead>
                        <tr>
                            <th>Employee</th>
                            <th>Department</th>
                            <th>First IN</th>
                            <th>Last OUT</th>
                            <th>Hours</th>
                            <th>Punctuality</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($rows as $row): ?>
                            <?php
                            $status = strtoupper($row["status"] ?? "NOT_SEEN");
                            $punctuality = strtoupper($row["punctuality"] ?? "NOT_SEEN");
                            ?>
                            <tr>
                                <td>
                                    <a
                                        href="profile.php?id=<?= rawurlencode($row["employeeId"] ?? "") ?>"
                                        style="text-decoration:none;font-weight:800;"
                                    >
                                        <?= htmlspecialchars($row["name"] ?? "Unknown Employee") ?>
                                    </a><br>
                                    <span style="color:var(--muted);font-size:.76rem;">
                                        <?= htmlspecialchars($row["employeeId"] ?? "") ?>
                                    </span>
                                </td>
                                <td><?= htmlspecialchars($row["department"] ?? "Unassigned") ?></td>
                                <td><?= htmlspecialchars($row["firstIn"] ?? "--") ?></td>
                                <td><?= htmlspecialchars($row["lastOut"] ?? "--") ?></td>
                                <td><?= number_format((float)($row["completedHours"] ?? 0), 2) ?>h</td>
                                <td>
                                    <?php if ($punctuality === "LATE"): ?>
                                        <span class="badge" style="color:#fde68a;background:var(--amber-soft);">
                                            Late <?= (int)($row["minutesLate"] ?? 0) ?>m
                                        </span>
                                    <?php elseif ($punctuality === "ON_TIME"): ?>
                                        <span class="badge active">On time</span>
                                    <?php else: ?>
                                        <span class="badge inactive">Not seen</span>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <span class="badge <?= $status === "IN" ? "in" : ($status === "OUT" ? "out" : "inactive") ?>">
                                        <?= htmlspecialchars(str_replace("_", " ", $status)) ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php endif; ?>
        </section>
    </main>
</div>
</body>
</html>
